### ISSUE TITLE
some MenuItem is disappeared

### ISSUE THREAD

**Issue by chineselzh** [TurboPack/MustangpeakVirtualshellTools#1]
**What steps will reproduce the problem?**
1. run demos \ Virtual Explorer 
2. select one folder or file
3. right click

**What is the expected output? What do you see instead?**
some MenuItem is disappeared.
img like this:![](https://raw.githubusercontent.com/chineselzh/MyPhoto/master/SoftBug/mustangpeakvirtualshelltools bug.png)

**What version of the product are you using? On what operating system?**
xe7 and win8.1

**Please provide any additional information below.**
how to fix it? thank you!
by the way,when can it support xe8?

**Comment by JimKueneman** [comment]
Hi,
  This is a problem with Windows.  I am going to guess you are running Windows 64 bit and FreeArc has only supplied a 32 bit shell extension with their product.  Windows Explorer is able to bypass new security features and load a 32 bit extension into 64 bit Explorer.  It will NOT allow other programs to do the same.  The only fix is to have FreeArc build a 64 bit dll of their extension.
Jim
