### ISSUE TITLE
Requires wrong?

### ISSUE THREAD

**Issue by luebbe** [TurboPack/MustangpeakVirtualshellTools#14]
Shouldn't the last line in 'requires' read:
`  VirtualTreesR;`

instead of:
`  VirtualTreesDR;`

for me it doesn't compile with VirtualTreesDR; after having installed virtual treeview from the current GitHub sources.

**Comment by pyscripter** [comment]
It is meant to be used with TurboPack VirtualTreeView which has different package names I am afraid.  

Just change the package name to use with the JAM-Software one.  That's what I do.

**Comment by luebbe** [comment]
Ouch, I always thought they were identical.

That's exactly what I did.
