### ISSUE TITLE
Windows 11 crash

### ISSUE THREAD

**Issue by mhietan** [TurboPack/MustangpeakVirtualshellTools#18]
Delphi 10.4 update 2+patches installed.
Virtual-Treeview is 7.6 version.
Windows 11 build 22000.65

1. Drop VirtualExplorerTreeview1 in to Form.
2. Drop button in to Form and code: 
procedure TForm1.Button1Click(Sender: TObject);
begin
  VirtualExplorerTreeview1.Active:=True;
end;
3. Compile it to 64bit app and try run.
5. After button click: Float invalid operation occurs and app crashes.
---------------------------
Debugger Exception Notification
---------------------------
Project Project1.exe raised exception class $C0000090 with message 'c0000090 FLOAT_INVALID_OPERATION'.
---------------------------
Break   Continue   Help   
---------------------------

:00007FFD0B64C268 ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B63C6E0 ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B63C432 ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B6D3880 ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B6CA03D ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B6C1FAC ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B63B3BE ; C:\WINDOWS\System32\ESENT.dll
:00007FFD0B63B25B ; C:\WINDOWS\System32\ESENT.dll
:00007FFD12952604 ; C:\WINDOWS\System32\fhcat.dll
:00007FFD1294A5DE ; C:\WINDOWS\System32\fhcat.dll
:00007FFD1293AED7 ; C:\WINDOWS\System32\fhcat.dll
:00007FFD1293A137 ; C:\WINDOWS\System32\fhcat.dll
:00007FFD1293AB54 ; C:\WINDOWS\System32\fhcat.dll
:00007FFD1FAE37C8 ; C:\WINDOWS\System32\combase.dll
:00007FFD1FAD22AF ; C:\WINDOWS\System32\combase.dll
:00007FFD1FAE3E9C ; C:\WINDOWS\System32\combase.dll
:00007FFD1FB6B008 ; C:\WINDOWS\System32\combase.dll
:00007FFD1FB71ECC ; C:\WINDOWS\System32\combase.dll
:00007FFD1FB675FE ; C:\WINDOWS\System32\combase.dll
:00007FFD1FAE39F4 ; C:\WINDOWS\System32\combase.dll
:00007FFD1FAD22AF ; C:\WINDOWS\System32\combase.dll
:000000000014D3A0 ; ???
:00007FFD1FAE0F30 ; C:\WINDOWS\System32\combase.dll

**Comment by romankassebaum** [comment]
I updated the TVirtualTreeView and could not reproduce the issue. Could you please check with the updated components?

**Comment by mhietan** [comment]
Windows 11 (10.0.22000.100) (KB5004300):
1. Downloaded as zip, updated VirtualShellTools and updated VirtualTreeview.
2. Cleaned all traces from previous installation
3. Installed those components
4. Compiled above mini 64 bit demo and trying to run it.
5. Still Crashing after clicking button.

**Comment by mhietan** [comment]
Windows 11 Insider Preview 22449.1000 (rs_prerelease).
now it works. It was clearly Windows 11 fault.

**Comment by pyscripter** [comment]
Great!
