### ISSUE TITLE
Some classes have a Tag property that is not 64bit safe

### ISSUE THREAD

**Issue by brianjford** [TurboPack/MustangpeakVirtualshellTools#2]
Some of the classes have a Tag property declared as Integer and then pointers are stored into it.  This causes issues when using the component in 64bit mode; and I believe these Tag's should be converted to NativeInt.

e.g. The line in function TShellToolButton.GetImageIndex:  Request.Tag := Integer(Self);

**Comment by romankassebaum** [comment]
I changed all Tag properties from Integer To NativeInt.

**Comment by brianjford** [comment]
Thanks Roman,  It's awesome to see these components still being maintained.
