### ISSUE TITLE
VirtualExplorerListView and Shell Column settings form missing proper content

### ISSUE THREAD

**Issue by mhietan** [TurboPack/MustangpeakVirtualshellTools#20]
Hi,

Column settings form should display all columns what can be selected.

Wrong:
![image](https://user-images.githubusercontent.com/37412701/171216465-714522c0-6453-4cc5-a819-38edd815c92d.png)

Correct:
![image](https://user-images.githubusercontent.com/37412701/171216822-46747810-1797-4793-994e-e9bbb8b34e65.png)

**Comment by romankassebaum** [comment]
Could you please send me a PM?

**Comment by mhietan** [comment]
Check email :)

**Comment by mhietan** [comment]
Latest fix helped. It works okay now.
