### ISSUE TITLE
Mistake in Unit VirtualResources.pas

### ISSUE THREAD

**Issue by RenaldoGlobe** [TurboPack/MustangpeakVirtualshellTools#22]
In the Interface part, there is a Mistake:
const
  WM_VETBASE = WM_APP + 51;
  WM_SHELLNOTIFY = WM_VETBASE;                 // Change in the Shell occured
  WM_VTSETICONINDEX = WM_VETBASE + 1;          // Threaded Icons
  WM_INVALIDFILENAME = WM_VETBASE + 2;         // VET
  WM_SHELLNOTIFYTHREADQUIT = WM_VETBASE + 3;   // ShellNotifier
  WM_CHANGENOTIFY_NT = WM_VETBASE + 4;         // ShellNotifier
  WM_CHANGENOTIFY = WM_VETBASE + 5;            // ShellNotifier
  WM_SHELLNOTIFYTHREADEVENT = WM_VETBASE + 6;  // ShellNotifier
  WM_SHELLNOTIFYRELEASE = WM_VETBASE + 7;      // ShellNotifier
  WM_REMOVEBUTTON = WM_VETBASE + 8;            // VirtualShellToolbar
  WM_CHANGENOTIFY_CUSTOM = WM_VETBASE + 9;
  WM_UPDATESCROLLBAR = WM_VETBASE + 10;       // Signal TDropDownWnd to update scrollbar
  WM_VTSETTHREADMARK = WM_VETBASE + 11;
  **WM_FOLDERCHANGENOTIFY = WM_VETBASE + 11;  <----- have to be 12 and not 11**

**Comment by romankassebaum** [comment]
Fixed. Please check.

**Comment by RenaldoGlobe** [comment]
Yes, it is ok.


Am .06.2022, 22:42 Uhr, schrieb Roman Kassebaum ***@***.***>:
