### ISSUE TITLE
MPCommonUtilities isWin7 Function

### ISSUE THREAD

**Issue by RenaldoGlobe** [TurboPack/MustangpeakVirtualshellTools#23]
In the UNIT **"MPCommonUtilities.pas"** the FUNCTION **"isWin7"** ends with the result FALSE, if the used operating system is Windows 10.
Unfortunately the result is used for example by the **"TVirtaulExplorerTree"**, were you can select the property **"foIncluseSuperHidden"** under **"FileObjects"**. 

You cannot select the "foIncluseSuperHidden" property, while the function "isWin7" resulting FALSE.  
I posted this Issue at this place, because it affects the VirtualExplorerTree.

**Comment by romankassebaum** [comment]
I fixed it. Please check.

**Comment by RenaldoGlobe** [comment]
Yes, it ist ok.


Am .06.2022, 22:40 Uhr, schrieb Roman Kassebaum ***@***.***>:
