### ISSUE TITLE
VirtualTreesDR is wrong for the latest version of VirtualTreeView

### ISSUE THREAD

**Issue by luebbe** [TurboPack/MustangpeakVirtualshellTools#26]
With the latest version of VirtualTreeView the package has been renamed to VirtualTreesD. So you should change the `requires` clauses in the .dpk files where appropriate.

**Comment by romankassebaum** [comment]
It depends on the VirtualTreeView. The version from Joachim Marder is called "D" and "R", whereas the TurboPack version uses "DD" and "DR".

**Comment by luebbe** [comment]
Why did it ever work before then? I never used the TurboPack TreeView and I don't remember having to change the .dpk file in VirtualShellTools. Thanks for the Info. Hopefully I'll remember it upon the next Delphi full install :)

**Comment by RomanFileCenter** [comment]
Is it possible that you have installed the TurboPack version via GetIt, so that Delphi can find the packages?

**Comment by romankassebaum** [comment]
Is it possible that you have installed the TurboPack version via GetIt, so that the compiler could find the packages?

**Comment by luebbe** [comment]
No, I only use getit for IDE plugins and install all components directly from source. Yesterday I also saw that there is a JAM-VT package, which requires VirtualTreesD instead of "DD". Obviously my brain was fixed on Alexandria or 10.4.+, so I missed it :)
Haven't tried to compile it, because at a first glance the relative paths inside the JAM-VT dpk seemed wrong compared to the Alexandria package.
BTW, why don't you use "libsuffix auto" starting from Delphi 10.4.+ on? It seems to work reliably since then.

**Comment by romankassebaum** [comment]
Does "libsuffix auto" also work for C++ Builder?

**Comment by luebbe** [comment]
Sorry, don't know. I never used CPP Builder.

**Comment by romankassebaum** [comment]
I just checked and it looks like it does.
