### ISSUE TITLE
TVirtualExplorerTreeview thrown AV when Active := True;

### ISSUE THREAD

**Issue by GallaherMike** [TurboPack/MustangpeakVirtualshellTools#3]
Delphi 10 Seattle Update 1

Use GetIt to install TurboPack VirtualShellTools and TurboPack VirtualTree.

New project
Drop a TVirtualExplorerTreeview on the main form
Change the Active property to TRUE
AV

Digging through the code it looks like the problem is in TCustomVirtualExplorerTree.DoInitNode specifically the line

FreeAndNil(Data.ColumnManager);

is throwing the AV. It looks like the Data.ColumnManager is passing the Assigned check but is not actually a TColumnManager instance so the free and nil

**Comment by romankassebaum** [comment]
You should download the latest versions from GitHub since Embarcadero doesn't update GetIt in time.

**Comment by GallaherMike** [comment]
Thanks pulled the tip and everything is good.
