### ISSUE TITLE
problems with the installation MustangpeakVirtualshellTools 

### ISSUE THREAD

**Issue by lbWishmaster** [TurboPack/MustangpeakVirtualshellTools#31]
I had to reinstall Delphi, so I grabbed the last versions of TurboPack/MustangpeakVirtualshellTools  +  JAM-Software/Virtual-TreeView
now when I try to install them I get the error message. 

"[dcc32 Fatal Error] VirtualShellToolsD.dpk(39): E2202 Required package 'VirtualTreesDR' not found"

What has changed?

**Comment by romankassebaum** [comment]
Mustangpeak uses the TurboPack version of the VirtualTree (https://github.com/TurboPack/VirtualTreeView). You can try to use the  JAM version, but then you have to require the VirtualTreesR instead of VirtualTreesDR.

**Comment by NettixCode** [comment]
> Mustangpeak uses the TurboPack version of the VirtualTree (https://github.com/TurboPack/VirtualTreeView). You can try to use the JAM version, but then you have to require the VirtualTreesR instead of VirtualTreesDR.

then dont give link to JAM version then in your installation notice.. there you give link to JAM version treeview : https://github.com/JAM-Software/Virtual-TreeView .. zzzzzz

**Comment by NettixCode** [comment]
@romankassebaum  are this virtualshelltools have an delphi 7 version ? where i can download ? i found the old one from google code but it give many error when try to install virtualshelltoolsD7.dpk ..

**Comment by romankassebaum** [comment]
There is no version for Delphi 7. You should move your code to 11.3.
