### ISSUE TITLE
Thumbnail image flipped

### ISSUE THREAD

**Issue by yeohray** [TurboPack/MustangpeakVirtualshellTools#36]
Using this [file](http://www.happydurian.com/downloads/file.mp3) as reference, using TVirtualExplorerEasyListView, when in thumbnail mode on Windows 10, the thumbnail image is displayed correctly.  On Windows 11, the image is flipped.  Is there some setting that I'm missing?

Thanks in advance.

Ray

**Comment by romankassebaum** [comment]
The link to your file does not work. And do you have a simple test project?

**Comment by yeohray** [comment]
I've fixed the link, and attached a simple test project.  Please place the mp3 in the same folder as the executable.
[thumbnail.zip](https://github.com/TurboPack/MustangpeakVirtualshellTools/files/13753721/thumbnail.zip)

**Comment by romankassebaum** [comment]
Here it looks fine. I attached a screenshot.

![Screenshot](https://github.com/TurboPack/MustangpeakVirtualshellTools/assets/4661614/c9e04fc7-664d-4d3b-b00d-e926f353076c)

Are you sure that we are using the same versions of MP?

**Comment by yeohray** [comment]
I updated CommonLib, ListView and VirtualShell to the latest master branches, but is still flipped on my Windows 11 machine.

![flipped](https://github.com/TurboPack/MustangpeakVirtualshellTools/assets/5498402/0a7ce96b-c435-4356-8ae9-5462590a35e1)

**Comment by romankassebaum** [comment]
I cannot reproduce the issue. Maybe you are mixing some libs.

**Comment by yeohray** [comment]
No worries, I'm using ImageEn to fix this now.
