### ISSUE TITLE
TVirtualExplorerTreeview thrown AV when Active := True;

### ISSUE THREAD

**Issue by cbl-it** [TurboPack/MustangpeakVirtualshellTools#4]
The same as mentioned in[ issues/3](https://github.com/TurboPack/MustangpeakVirtualshellTools/issues/3)
New project
Drop a TVirtualExplorerTreeview on the main form
Change the Active property to TRUE
AV
looks like the Error comes from here
FreeAndNil(Data.ColumnManager);
All needed Packages are using from here and not from the GetIt Packager
Delphi Berlin 10.1

Maybe the (Data) Object  are nil???

**Comment by romankassebaum** [comment]
Fixed.
