### ISSUE TITLE
Refuses to compile.

### ISSUE THREAD

**Issue by Bloodbat** [TurboPack/MustangpeakVirtualshellTools#5]
I am unable to compile Virtualshell Tools due to COLUMNDLG_CHKSTYLE : TCheckImageKind = ckXP; present in VirtualResources.pas, it seems the definition was present in VirtualTrees.pas from virtual tree view, but now it's gone. This was attempted using the latest SVN code found here for Virtual Treeview and the MustangPeak requirements, along with the Virtualshell Tools themselves. They can be forced to compile by changing the line to COLUMNDLG_CHKSTYLE : TCheckImageKind = ckSystemDefault; that may lead, however, to an AV when the property "Active" is set to true, it could be unrelated, but I am unable to verify. The details of the AV:
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.GetImageSize + $9D
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.GetImageSize + $98
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.GetDisplayRect + $2DA
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.ScrollIntoView + $BF
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.DoFocusNode + $1A8
{VirtualShellToolsD240.bpl} Virtualexplorertree.TCustomVirtualExplorerTree.EnableChangeNotifier + $32
{VirtualTreesDR240.bpl} Virtualtrees.TBaseVirtualTree.SetFocusedNode + $19
{VirtualShellToolsD240.bpl} Virtualexplorertree.TCustomVirtualExplorerTree.RebuildRootNamespace + $17A
{VirtualShellToolsD240.bpl} Virtualexplorertree.TCustomVirtualExplorerTree.ActivateTree + $23
{VirtualShellToolsD240.bpl} Virtualexplorertree.TCustomVirtualExplorerTree.SetActive + $34
This was done with Delphi 10.1 Berlin.

**Comment by olegchensky** [comment]
Exact the same problem and the same AV

**Comment by olegchensky** [comment]
I can compile and install it, but the same AV

**Comment by romankassebaum** [comment]
I made the code compilable but got the same AV. The reason are changes in the VirtualTreeView.

I contacted the author of the VirtualTreeView and asked some questions. I hope he can help me.

**Comment by romankassebaum** [comment]
What I currently can say is that the changes in the VTV break existing code. Without further information from Joachim Marder there is no chance to fix this.
The only thing you can do now is to revert the VTV.

**Comment by Bloodbat** [comment]
Going back to the Virtual Treeview 6.3 merge did the trick, thanks :)

**Comment by romankassebaum** [comment]
I hope I could fix the issue. Please test and try.

**Comment by Bloodbat** [comment]
Can confirm it works, thanks a lot :)

**Comment by olegchensky** [comment]
Works! Thanks!
