### ISSUE TITLE
Column names after previous fix.

### ISSUE THREAD

**Issue by Bloodbat** [TurboPack/MustangpeakVirtualshellTools#6]
After doing some more testing, while the Virtualshell Tools do compile now and don't AV, as stated in last issue, whenever I click on the column names to select visible columns, I get "Error reading VSTColumnNames.CheckImageKind: Invalid Property Value"

**Comment by romankassebaum** [comment]
Do you have a callstack or a test project?

**Comment by Bloodbat** [comment]
Here's a test project
[treetest.zip](https://github.com/TurboPack/MustangpeakVirtualshellTools/files/509887/treetest.zip)

**Comment by romankassebaum** [comment]
Works perfectly for me.

Is it possible that you haven't recompiled the designtime package so that the IDE always adds an invalid property value to the dfm file?

**Comment by Bloodbat** [comment]
I just rebuilt everything (Virtual Treeview, MustangPeak Common Lib, Easy List View and Virtual Shell Tools) and the error persists.

**Comment by romankassebaum** [comment]
Please check which designtime package is loaded by the IDE. I guess it is not the one you are compiling.

**Comment by Bloodbat** [comment]
The proper package is loaded, I'm under Windows 7, if that has anything to do with it.

**Comment by romankassebaum** [comment]
I don't think that Win7 is a problem.

I have no idea what's wrong with your IDE.

**Comment by Bloodbat** [comment]
I'm not exactly sure what was the problem, but it was solved by opening ColumnForm.dfm, getting the error, telling Delphi to "ignore" it and open the form anyway and recompiling the tools...now it works. Thanks for your help :).

**Comment by romankassebaum** [comment]
Then I know what has happened. The old version of the lib stored an for the new version invalid prop in the dfm file.
