### ISSUE TITLE
GraphicEx Support

### ISSUE THREAD

**Issue by brianjford** [TurboPack/MustangpeakVirtualshellTools#8]
This is not an "issue" but more of a question.  Just wondering why GraphicEx support was removed?  We were using that to provide thumbnails for PNG and TGA files.  I see ImageEn was also temporarily removed but later put back in, however GraphicEx was never put back..  

Thanks, and sorry for posting this here..  Is there a message board or something where we can discuss the TurboPack components?

**Comment by romankassebaum** [comment]
No special reason. Thought that no one uses it any longer.

If you have some time it would be nice if you could readd it.

**Comment by brianjford** [comment]
Awesome, thanks Roman.  I'll try to add it back in the near future.

**Comment by pyscripter** [comment]
GraphicEx  support was part of VirtualExplorerListviewEx which was not part of this package and no longer available.  PNG support is built in Delphi now.
